# Basic
title: Johns space
subtitle: A blog for John
welcome_message: <a href="https://heroneo.github.io" target="_blank">Welcome my blog</a>
description: Just My Blog.
creator: <a href="http://onev.cat">@onevcat</a>

url: "http://heroneo.github.io"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: slate

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
#    - {title: Projects, description: My Projects, url: 'http://project.onevcat.com'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
 social:
#    weibo: john
    github: heroneo
    twitter: heroneo
#    gplus: 00000000000
    mail: heroneo@163.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
